---
- name: win_regedit module add demo
  hosts: windows
  become: false
  gather_facts: false
  vars:
    reg_path: 'HKLM:\Software\Test'

  tasks:
    - name: Create or update a registry key on Windows host
      ansible.windows.win_regedit:
        path: "{{ reg_path }}"
        state: absent
