---
- name: Users exist and are in correct groups
  hosts: all
  tasks:
    - name: Users exist and are in correct groups
      ansible.builtin.user:
        name: "{{ item.name }}"
        state: present
        groups: "{{ item.group }}"
      loop:
        - name: alice
          group: "wheel"
        - name: bob
          group: "root"
        - name: charlie
          group: "admin"