---
- name: check services
  hosts: all
  tasks:
  - name: https and mariadb are running
    ansible.builtin.service:
      name: "{{ item }}"
      state: started
      enabled: true
    loop:
      - httpd
      - mariadb
